### ISSUE TITLE
Example: Methods defined on non-directive controller to be called by wrapped React component

### ISSUE THREAD

**Issue by jjmasse** [jjmasse/angular-react-migration#2]
I have been struggling a bit with a pattern where methods are passed through a directive from a non-directive controller, through a directive and down into a React component to be called.

#### Example
```
class SomeController {
  constructor(foo) {
    this.foo = foo
  }

  handleClick() {
    this.foo = 'Clicked'
  }
}
```

#### Implementation view
```html
<div ng-controller="sample-controller as controller">
  <good-directive handleClick="controller.handleClick"></good-directive>
</div>
```

#### Some directive
```
function goodDirective() {
  return {
    restrict: 'E',
    scope: {
      handleClick: '&',
    },

    renderReact(element, props) {
      ReactDOM.render(
        <SomeComponent
          handleDidClick={props.handleClick}
        />,
        element)
    },

    link(scope, element, attrs) {
      const props = {
        handleClick: scope.handleClick,
      }

      this.renderReact(element[0], props)
    }
  }
}
```

### Issue
Passing functions in this way does not seem to yield the result of actually calling the method passed.   However, representing the methods as part of the body of the directive seems to work.

**Comment by abachuk** [comment]
It could be related to scope `handleClick: '&'` also could try `bindToController: true` https://blog.thoughtram.io/angularjs/2015/01/02/exploring-angular-1.3-bindToController.html#binding-to-controllers-with-bindtocontroller

**Comment by jjmasse** [comment]
@abachuk thank you!  

I figured out my problem was actually related to how I was passing the method down through to the wrapping directive.

```
<MyDirective callBack="callbackFunc()"></MyDirective>
// needs to change to
<my-directive call-back="callbackFunc()"></my-directive>
```
